### ISSUE TITLE
UpdateMsg operations: Minimal set of changes after executing a block?

### ISSUE THREAD

**Issue by SoujanyaPonnapalli** [RainBlock/rainblock-protocol#16]
Verifier should send a minimal set of update operations for a block of transactions.

For example:
```
Case-1: If a block contains multiple transactions updating an account's value:
Verifier should send one `ValueChangeOp` corresponding to the updated account
```

```
Case-2: If a block contains multiple transactions updating the account's storage:
Verifier should send one `ExecutionOp` reflecting all the `StorageUpdates`
```

```
Case-3: If a block contains multiple transactions updating an account's value and 
has one final transaction that deletes the account:
Verifier should send one `DeletionOp`
```

```
Case-4: If an account is created and updated by multiple transactions in the same block: 
Verifier should send one create-op corresponding to the updated balance and nonce
```
And similarly for other operations...

Storage currently assumes that one update operation is sent per account. We need this to reduce the UpdateMsg size and the RPC serialization/deserialization overheads as well. 

For supporting this; we need CreateOp to have nonce field and update the verifier accordingly.
Let me know your thoughts @no2chem

**Comment by no2chem** [comment]
This is the current case and doesn't require changes to the protobuf, does it? The coalescing should be performed by the verifier (which it doesn't do yet).

I would suggest actually simplifying the entire scheme, create a single message UpdateMsg with the following fields,
```
message UpdateMsg {
  bytes account; // 20 bytes, BE account number
  bytes balance; //  32 bytes, BE new balance, or empty if unchanged, or all FFs if deleted.
  uint32 updates; // one for each nonce update
  repeated StorageUpdate storage_updates; // Storage updates, if any.
  bytes code; // Code, only applicable for creation of a contract account.
}
```

**Comment by SoujanyaPonnapalli** [comment]
> This is the current case and doesn't require changes to the protobuf, does it? The coalescing should be performed by the verifier (which it doesn't do yet).

There is one change required in the protobuf too.
If an account is created and modified in the same block, the verifier has to send one CreationOp with updated nonce and balance. Our CreationOp doesn't have a nonce field. That is the only modification required on this repo.

I prefer not having one UpdateMsg as suggested, because accounts that have only modified balance and nonce need not have StorageUpdate fields at all. So I think, having different messages is better.

**Comment by SoujanyaPonnapalli** [comment]
We should have nonce field in `CreationOp` and `ExecutionOp`. That is probably the only change required to support the coalescing of the update ops. We don't need to significantly change the API.

Let me know what you think @no2chem.

**Comment by no2chem** [comment]
I think we should have only a single message still. It's actually pretty annoying to place each op into the UpdateOp container, and I think it has some overhead, all fields are optional in protobuf by default anyway. Maybe you can quickly test what the size of a single message vs multiple would be?

**Comment by SoujanyaPonnapalli** [comment]
I tried sent an update call to the server with one CreationOp, ExecutionOp, DeletionOP and ValueOp.
Every message has only the account address set to a constant value. The rest of the fields are left empty. I measured the size of call arguments in bytes on the server side.

```
Create Request size :  9902 (+272)
Value Request size :  9756 (+126)
Execution Request size :  9824 ( +194)
Delete Request size :  9630 ( +0)
```

Also the empty request sizes in bytes:
```
CreationOp :  782 (+272)
ValueChangeOp :  636 (+126)
ExecutionOp :  704 (+194)
DeletionOp :  510 (+0)
```

So converting every DeletionOp also as CreationOp will add around 270 Bytes per update operation.
What do you think @no2chem ?

**Comment by no2chem** [comment]
@SoujanyaPonnapalli These numbers seem really high and don't make much sense? How are you producing these numbers...  Why would an empty message take 782 bytes? This doesn't quite pass the sanity check.

**Comment by no2chem** [comment]
@SoujanyaPonnapalli Because of the large numbers you gave, I had to run my own tests.

https://gist.github.com/no2chem/c303c708b4101d1bef1b488d954d466f

```
Value change op (original=58) (new=56) (diff=2)
Delete op (original=24) (new=24) (diff=0)
Create op (original=83) (new=81) (diff=2)
Execution op (original=131) (new=128) (diff=3)
Create op w updates (w updates=83) (simple=83) (diff=0)
```

The last line is your proposal compared to my proposal, which both take 83 bytes, with an account, balance, test contract and updates populated. As you can see, it takes the same amount of bytes as the message I proposed. 

The first four lines are my proposal. You can see that the original use of `oneof` keyword adds an additional 2-3 bytes of overhead in some cases. This isn't a lot, but it would add up if there are a lot of updates.

I'm still really unsure how you get +270 bytes per operation (that's crazy), or how you measured any of the sizes... 9KB for a create request?... Maybe I'm missing something here...?

I would suggest moving forward with just adopting the simplified message scheme and eliminating the use of `oneof`. I'll open a PR.

**Comment by SoujanyaPonnapalli** [comment]
I was away for a few hours. Sorry for the delay in responding to your question.
I see that you measured the size of the serialized message. The difference was I measured the size of the unserialized message. I agree measuring serialized message makes more sense and gives us an idea of the network overheads.

Let me know if you want me to send in a PR with the simplified scheme.
I will have to change the storage node to support the modified protobuf anyway, so I can work on it.

**Comment by no2chem** [comment]
@SoujanyaPonnapalli how do you measure the length of an unserialized message?

**Comment by SoujanyaPonnapalli** [comment]
@no2chem I used [sizeof](https://www.npmjs.com/package/sizeof) to measure the size of unserialized messages

**Comment by no2chem** [comment]
@SoujanyaPonnapalli I see. You realize that (really old) package just serializes the entire object into JSON and then measures the size of the JSON string... right?... anyway, I'll open the PR.

**Comment by SoujanyaPonnapalli** [comment]
I didn't realize that was what sizeof was doing. That makes sense now.
Thanks for the information.
